### ISSUE TITLE
New project, but no master branch?

### ISSUE THREAD

**Issue by fniephaus** [j4yk/Squot#42]
When adding a new project, the tool does not display that there is a `master` branch. Not sure what needs to be done here.

**Comment by j4yk** [comment]
There really is no master branch. When you do `git init`, there is also no branch at first, but the master reference is created automatically when you do the first `git commit`.

When you inspect the objects, the behavior is confusing though. The SquotWorkingCopy is initialized with the repository's defaultHistorian, which is refs/heads/master, but the reference (file) is not created until the historian gets a new version assigned (which updates the reference). Since the reference does not exist in the git repository (as a file) yet, it is not listed in the branch list, even though there is an instance of SquitHistorian (but unbeknownst to the SquitRepository).

**Comment by j4yk** [comment]
We cannot create a reference in the repository right away, because there is no commit to which this reference could point. So the only way to simulate that a branch does already exist, would be to let the UI show a "fake" branch (named after the working copy's historian) when the list of historians is empty.

**Comment by fniephaus** [comment]
Okay, so this is intended behavior...I guess #45 is the real reason I couldn't get started with my little demo project for Tuesday...
